[package]
name = "efm32pg1b-pac"
version = "0.1.0"
authors = ["Bogdan Olar <olar.bogdan.dev@gmail.com>"]
edition = "2018"
description = "Peripheral access API for Silicon Labs EFM32PG1B microcontrollers"
keywords = ["arm", "cortex-m", "efm32", "efm32pg1b", "svd2rust"]
categories = ["embedded", "hardware-support", "no-std"]
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/BogdanOlar/efm32pg1b-pac"

[dependencies]
bare-metal = "0.2.5"
cortex-m = "0.6.2"
vcell = "0.1.2"

[dependencies.cortex-m-rt]
optional = true
version = "0.6.12"

[features]
rt = ["cortex-m-rt/device"]
